version: 2

jobs:
  test:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Unit Tests
          command: npm run test

  lint:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Eslint
          command: npm run lint

workflows:
  version: 2
  test_and_lint:
    jobs:
      - test
      - lint:
          requires:
           - test
